- name: Create a single LXC container on Proxmox
  hosts: proxmox
  gather_facts: false
  become: true

  vars:
    lxc_vmid: 999
    lxc_hostname: test-lxc
    lxc_template: "/var/lib/vz/template/cache/ubuntu-25.04-standard_25.04-1.1_amd64.tar.zst"
    lxc_cores: 2
    lxc_memory: 1024
    lxc_swap: 512
    lxc_disk: 8
    lxc_bridge: vmbr0
    lxc_ip: 192.168.12.42/24
    gateway: 192.168.12.1
    lxc_root_password: "lxc-pass"  # <-- Set root password for container

  tasks:

    - name: Ensure pct command exists
      ansible.builtin.command: which pct
      register: pct_check
      failed_when: pct_check.rc != 0

    - name: Create LXC container
      ansible.builtin.shell: |
        pct create {{ lxc_vmid }} {{ lxc_template }} \
          --hostname {{ lxc_hostname }} \
          --cores {{ lxc_cores }} \
          --memory {{ lxc_memory }} \
          --swap {{ lxc_swap }} \
          --net0 name=eth0,bridge={{ lxc_bridge }},ip={{ lxc_ip }},gw={{ gateway }} \
          --rootfs local:{{ lxc_disk }} \
          --password {{ lxc_root_password }} \
          --start 0
      args:
        executable: /bin/bash

    - name: Start LXC container
      ansible.builtin.shell: /usr/sbin/pct start {{ lxc_vmid }}
      args:
        executable: /bin/bash

    - name: Show LXC info
      ansible.builtin.debug:
        msg: "Created LXC {{ lxc_hostname }} with VMID {{ lxc_vmid }}, IP {{ lxc_ip }}, root password {{ lxc_root_password }}"
